version: '3.3'

services:
  rides:
    container_name: rides
    image: rides
    restart: always
    environment:
      - TEAM_NAME=CC_0024_0162_1618_1640 
    volumes:
      - .:/todo
    build: .
    command: python ride.py 
    expose:
      - "80"
    ports:
      - 80:80

      